# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "43dd49cffb45682dddc07c4fa6687663"
name = "dropicon"
application_url = "https://varied-earliest-pattern-combination.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dropi-v1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_locales,read_locations,read_markets,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://varied-earliest-pattern-combination.trycloudflare.com/auth/callback",
  "https://varied-earliest-pattern-combination.trycloudflare.com/auth/shopify/callback",
  "https://varied-earliest-pattern-combination.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
