# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f8b388dde42ce28875159df6a3e9364d"
name = "dropi-v01"
application_url = "https://mainly-tar-currently-yale.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dropi-v1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_locales,read_locations,read_markets,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://mainly-tar-currently-yale.trycloudflare.com/auth/callback",
  "https://mainly-tar-currently-yale.trycloudflare.com/auth/shopify/callback",
  "https://mainly-tar-currently-yale.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-07"

[pos]
embedded = false
